# Generated by Django 4.2.16 on 2024-10-27 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите правильное имя пользователя.', regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
